#!/bin/bash

# Optimize Images
# Program: jpegtran

IMG_PATH=style/img/poets/profile
cd $IMG_PATH

ls | grep ".jpg" |
    while read f; do
	jpegtran -progressive $f > $f.0
	jpegtran -optimize $f.0 > $f.1
	rm $f $f.0
	mv $f.1 $f
	echo "$f OPTIMIZED."
    done
