#!/usr/bin/node

/* Convert Markdown files to HTML. */

const files = ['dev/tools/CONTRIBUTING/CONTRIBUTING',
	       'dev/tools/dev']

const fs = require('fs')
const showdown = require('showdown')
const converter = new showdown.Converter()

for(const file of files) {
	const md = fs.readFileSync(`${file}.md`).toString()
	const html = converter.makeHtml(md)
	fs.writeFileSync(`${file}.html`, html)
	console.log(`${file}.md -> ${file}.html`)
}
